- .travis.yml
- backend/test-requirements.txt
Update the Travis config for the latest versions of Python, change to pytest, and add JS tests
> Change Travis config to support both Python and JS

- frontend/src/run-list.js
Added clickable filtering to the component and env pills in the run list, essentially identical to that done in the result list.
> Made run-list component and env pills clickable for filtering

- frontend/src/app.js
> Add a link to the docs on the about modal

- frontend/src/app.js
> Add trademark and file retention policy to About modal

- frontend/src/app.js
* Make links on the About modal open in a new tab
* Add a link for submitting an upstream issue
I said `Report Bugs` so we can add a link to our JIRA project once we get it.
> Add link to submit upstream issue, make links open in new tab

- frontend/src/widgets/genericarea.js
- frontend/src/widgets/genericbar.js
> Add a tooltip to the generic area chart

- frontend/src/components/filtertable.js
- frontend/src/components/result.js
- frontend/src/run.js
- frontend/src/utilities.js
Depends on #16, so that one needs a review first. Here are some screenshots:
> Allow filtering by exception name on classification table

- frontend/src/app.css
- frontend/src/views/jenkinsjobanalysis.js
- Remove browser focus outline
- Fix layout of switch
> Style tweaks

- frontend/src/components/classify-failures.js
- frontend/src/components/index.js
- frontend/src/run.js
This PR: 
* Converts classification table into its own component
* Makes the classification table on the run details page use that component
A future PR will add an unfiltered version of the table somewhere in the UI.
> Convert failure classification table into its own component 

- frontend/src/app.js
> Add link to JIRA issues.redhat.com

- backend/ibutsu_server/widgets/jenkins_heatmap.py
Before: 
After:
**Important note:** This is kind of a quick and dirty fix because it renders the value that is selected for `builds` inaccurate. For example, say a jenkins builds has failed 4 times in a row and then succeeds on the 5th time. The widget will display ONLY the 5th build, and not the 4 builds previous to the failures.
The latter behavior will require a more substantial rewrite of the aggregation used to create this widget.
> [heatmap] Don't show columns in which all the plugins failed

- frontend/src/views/jenkinsjobanalysis.js
> Fix styling of count skips on Jenkins Job Analysis page

- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/tasks/queues.py
- backend/setup.py
- frontend/package.json
* Fix a small celery error `Cannot mix new and old setting keys`
> Version 1.10.2

- backend/ibutsu_server/db/base.py
- backend/ibutsu_server/widgets/result_summary.py
Need to test with a DB with more rows than I currently have, I expect we will need to use some page_size like was originally there. 
I converted this one first because I thought it'd be the easiest.
> Convert the result summary widget to psql

- backend/ibutsu_server/controllers/report_controller.py
- backend/ibutsu_server/tasks/reports.py
> Allow reports to work with postgres

- backend/ibutsu_server/tasks/importers.py
Fixing the junit importer task for postgres.
> Fix the junit importer for postgres

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/db/base.py
- backend/ibutsu_server/filters.py
- frontend/src/constants.js
- frontend/src/utilities.js
This allows us to filter by:
* `metadata.tags`
* `metadata.markers`
Special care must be given to these fields because they are arrays nested in the JSONB, so we must make use of some special operators in PSQL. 
https://www.postgresql.org/docs/9.5/functions-json.html#FUNCTIONS-JSONB-OP-TABLE
> Allow filtering by array fields

- backend/ibutsu_server/__init__.py
- backend/ibutsu_server/config.py
- backend/ibutsu_server/controllers/health_controller.py
- backend/ibutsu_server/tasks/__init__.py
- backend/ibutsu_server/tasks/reports.py
- backend/setup.py
- ibutsu-server-openshift.yaml
- Update the OpenShift template YAML
- Removed Dynaconf, cause it was just messing us around
> Update OpenShift template

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/scripts/mongo2postgres.py
- backend/ibutsu_server/widgets/jenkins_heatmap.py
- backend/ibutsu_server/widgets/jenkins_job_view.py
- frontend/src/views/jenkinsjob.js
This improves performance of the Jenkins Job View and the heatmap. 
Also add empty and error state to JJV
> Limit runs from which we determine the jenkins jobs

- backend/ibutsu_server/scripts/mongo2postgres.py
- backend/setup.cfg
- Use `iso8601.parse_date` (`fromisoformat()` is only 3.7+)
- Make migration limits configurable
> Migration limits

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/controllers/result_controller.py
- backend/ibutsu_server/controllers/run_controller.py
- backend/ibutsu_server/widgets/jenkins_heatmap.py
- frontend/src/components/result.js
- frontend/src/constants.js
- frontend/src/result-list.js
- frontend/src/utilities.js
Fetching 1000 runs is taking too long and affecting other pages in the app.
Also including some minor improvements for the heatmap and the run/results tables.
> Further performance improvements

- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
> Version 1.11

- frontend/src/app.js
- Make the selected object a Select object
- Drop the unused title property
Hopefully, this fixes bug #46
> Make the selected object a Select object

- backend/ibutsu_server/tasks/db.py
With Ibutsu's DB growing, we should begin pruning files once more. This PR updates the prune file task for PSQL.
> Update file pruning for PSQL

- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/test/test_importers.py
- backend/setup.py
- frontend/package.json
Include a test that accidentally got missed.
> Release 1.11.3

- backend/ibutsu_server/controllers/report_controller.py
- frontend/src/report-builder.js
> Fix bugs #78 and #79

- backend/ibutsu_server/constants.py
I missed a few fields in https://github.com/ibutsu/ibutsu-server/pull/85 :(
> Add summary.tests to the numeric_fields

- frontend/src/components/result.js
This is meant to address #88.
I was able to reproduce #88 locally and this appears to fix it.
> Fix loading of result component

- backend/ibutsu_server/widgets/jenkins_heatmap.py
- backend/ibutsu_server/widgets/jenkins_job_analysis.py
- backend/ibutsu_server/widgets/jenkins_job_view.py
- backend/ibutsu_server/widgets/result_summary.py
- backend/ibutsu_server/widgets/run_aggregator.py
- frontend/src/components/classify-failures.js
- frontend/src/views/jenkinsjobanalysis.js
- frontend/src/widgets/genericbar.js
- frontend/src/widgets/resultsummary.js
> Add xfail/xpass to widget calculations

- backend/ibutsu_server/__init__.py
- backend/ibutsu_server/auth.py
- backend/ibutsu_server/db/base.py
- backend/ibutsu_server/db/models.py
- backend/ibutsu_server/db/upgrades.py
- backend/setup.py
- Add model for dashboards
- Add dashboard_id to widget configs
- Create an upgrade system
- Add an initial upgrade to add dashboard_id column
- Add users for future use
> Prepare for configurable dashboards

- backend/ibutsu_server/controllers/dashboard_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
- Add the dashboard API to the OpenAPI spec
- Build the dashboard controller
- Update the OpenAPI spec to match the API (examples, field names, etc)
Needs #95 merged first.
> Build a new dashboard API

- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Create a UI to add dashboards and widgets
* Build the custom dashboards (#99)
* Build the dashboard API (#96)
* Create a way to upgrade databases on the fly
> Release 1.12.0

- frontend/src/components/delete-dashboard-modal.js
- frontend/src/components/index.js
- frontend/src/dashboard.js
* Adds a delete button for removing a dashboard (I just picked a "-" icon, let me know if you'd prefer a different style @rsnyman)
* Adds a delete dash modal
* On delete the user is taken to the empty dashboard state
> Add delete dashboard button

- docs/source/developer-guide/getting-started.rst
> Remove reference to MongoDB in docs

- frontend/src/app.js
- frontend/src/components/fileupload.js
> Pass project along with file when importing via the UI (closes #110)

- backend/ibutsu_server/openapi/openapi.yaml
> Update API spec to allow null values in Runs

- frontend/src/app.css
- frontend/src/components/result.js
- frontend/src/result.js
- frontend/src/run.js
- frontend/src/views/jenkinsjobanalysis.js
- frontend/yarn.lock
- On the Run and Result pages, "remember" the selected tab via the URL
- Update PatternFly React
- Make tabs "boxed"
- Fix up some style issues
> Remember tab + updates

- backend/ibutsu_server/controllers/artifact_controller.py
- backend/ibutsu_server/controllers/dashboard_controller.py
- backend/ibutsu_server/controllers/group_controller.py
- backend/ibutsu_server/controllers/import_controller.py
- backend/ibutsu_server/controllers/report_controller.py
- backend/ibutsu_server/controllers/result_controller.py
- backend/ibutsu_server/controllers/run_controller.py
- backend/ibutsu_server/controllers/widget_config_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/util/uuid.py
* Return 400 status if a `get` request receives a badly formed UUID
* Check if UUID is valid in Swagger UI by adding `format: uuid` to `openapi.yaml` where applicable
> Validate UUID in OpenAPI spec and controllers

- backend/ibutsu_server/db/upgrades.py
Adding an `upgrade_2` function to add indexes to aid in queries that search `metadata.tags` and `metadata.requirements`
> Add a upgrade function to add gin indexes on metadata.tags and metadata.requirements

- ocp-templates/pgsql-vacuum-cronjob.yaml
- ocp-templates/pgsql-vacuum-job.yaml
* Scheduled to run nightly at 8:01 pm EST, 1:01 am UTC
> Add cronjob/job for nightly vacuuming of database

- backend/ibutsu_server/tasks/importers.py
This is meant to solve: https://github.com/ibutsu/ibutsu-server/issues/92
cc @rsnyman
> Add support for legacy junit xml

- backend/ibutsu_server/controllers/dashboard_controller.py
Thanks @mshriver for reporting this one :smiley:
> Use 'id' rather than 'name' in dashboard GET

- backend/setup.py
- backend/test-requirements.txt
Updated some of the dependencies, to see if the updated dependencies work together.
> Update the Python dependencies

- ocp-templates/ibutsu-server-openshift.yaml
- ocp-templates/jobs/pgsql-backup-cronjob.yaml
- ocp-templates/jobs/pgsql-backup-job.yaml
- ocp-templates/jobs/pgsql-vacuum-cronjob.yaml
- ocp-templates/jobs/pgsql-vacuum-job.yaml
* fix the postgresql image
* move jobs to their own directory
> Small changes to OCP templates

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/controllers/result_controller.py
- backend/ibutsu_server/controllers/run_controller.py
- backend/ibutsu_server/controllers/task_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/tasks/__init__.py
- backend/ibutsu_server/tasks/query.py
- backend/ibutsu_server/util/query.py
* Add task API endpoint 
* Perform large queries in a task
* Return a 201 if page_size is above some limit
This work is for #163
> Perform large queries for results/runs in a task

- backend/docker/Dockerfile.backend
- backend/docker/Dockerfile.flower
- backend/docker/Dockerfile.mongodb
- backend/docker/Dockerfile.monitor
- backend/docker/Dockerfile.scheduler
- backend/docker/Dockerfile.worker
> Use Ubi8 images for dockerfiles

- backend/docker/Dockerfile.scheduler
- backend/docker/Dockerfile.worker
Make changes according to: 
https://github.com/sclorg/s2i-python-container/blob/master/3.6/README.md#3-prepare-an-application-inside-a-container
> Change the user when copying over the application

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/tasks/__init__.py
> Sync aborted runs from the last 3 hrs

- docs/source/developer-guide/getting-started.rst
> Add docs reference for backend/settings.yaml

- docs/source/user-guide/getting-started.rst
Just a quick little fix for a mispelling of ibutsu
> Fixed a spelling error

- ocp-templates/ibutsu-server-openshift.yaml
> Update default timeouts in OCP templates

- backend/ibutsu_server/tasks/importers.py
> Fix the archive importer

- backend/ibutsu_server/controllers/run_controller.py
> Fix bulk_update endpoint

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/widgets/result_aggregator.py
- frontend/src/components/classify-failures.js
- frontend/src/components/filtertable.js
- frontend/src/result-list.js
- frontend/src/run-list.js
- frontend/src/run.js
#201 
* Add a checkbox select filter that will automatically filter on `metadata.exception_name in <semi-colon-list>`
* Use the result_aggregator widget to easily fetch the exceptions
* Modify result_aggregator widget so we can directly pass run_id and make `days` optional
* Add support for hiding chips in `FilterTable`
* Hide `project_id` filter chip in results/runs table
Uploading filter-by-exception.mp4…
> Add a checkbox select filter for exceptions

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
- scripts/make-release.sh
* handle the `-beta` in some tags in the release script
> Release 1.13.4

- backend/ibutsu_server/controllers/project_controller.py
- backend/ibutsu_server/controllers/result_controller.py
- backend/ibutsu_server/controllers/run_controller.py
- backend/ibutsu_server/test/__init__.py
- backend/ibutsu_server/test/test_project_controller.py
- backend/ibutsu_server/util/projects.py
Addresses #235
- Ensure a project owner is added to the project when it's created
> Modify add_user_filter to filter on User projects

- frontend/src/user-profile.js
Add some project info to the profile page:
- list of projects a user is part of 
- show a label if a user is a super admin
- show a label if a user is a project owner
> Project info on profile page

- backend/ibutsu_server/controllers/widget_config_controller.py
- frontend/src/views/jenkinsjob.js
Addresses #242 
- and fix a small bug in the jenkins job view component
> Fix Jenkins Job View

- scripts/ibutsu-pod.sh
Update the `./scripts/ibutsu-pod.sh` script with the following:
- Create an admin user
- Create a project
- Standardise on echo
- Make the output prettier
> Default data in local pod deployment

- backend/ibutsu_server/__init__.py
Only superadmins should be able to kickoff tasks in this manner.
> Require superadmin token for running admin task

- frontend/src/login.js
* Also fix a small typo in login page
> Allow login by hitting <Enter>

- backend/ibutsu_server/tasks/db.py
Provide a way for Ibutsu superadmins to seed users and pair them with projects.
This should be merged after #249.
> Add a task for adding users/project owners

- frontend/src/user-profile.js
I noticed this issue in the stage env:
> Fix small FE bug on user profile page

- backend/ibutsu_server/tasks/importers.py
A single jUnit XML file is a single test run, refactor the importer to take this into account.
> Refactor jUnit XML importer

- frontend/src/login.js
- Add a spinner to the login button so that people can see that something is happening
> Show login progress feedback

- frontend/src/services/keycloak.js
The arguments were in the wrong place. Not sure why it worked locally, but now it is working against the stage SSO environment here.
> Fix keycloak login

- .gitignore
- backend/ibutsu_server/controllers/user_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
Adds a backend endpoint so superadmins can get a list of users. 
Partially addresses #261
> Add get_user_list endpoint

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/util/oauth.py
Get a user's primary e-mail on GitHub if they have no public e-mail address.
> Fix getting e-mail on GitHub

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Estimate count on test-history page
* Small improvements to the test history tab
* Hide username/password related components when user login is disabled (#279)
* Add test history tab to Result page (#276)
* Address some issues raised by static analysis (#278)
* Convert USER_LOGIN_ENABLED to bool if given as env var
* Get a user's primary e-mail on GitHub if they have no public e-mail address (#272)
* Add a way to disabled basic auth for non-superadmins
* Add get_user_list endpoint
* Fix keycloak login (#270)
* Update docker image names (#267)
* Show login progress feedback (#266)
* Add build_deploy script for App-SRE builds (#265)
* A single jUnit XML file is a single test run, refactor the importer to take this into account
* Some code refactoring after static analysis. (#245)
* …
> Release 2.0.0

- scripts/ibutsu-pod.sh
Fixed the ibutsu-pod script to run backend and frontend locally using podman.
> Fix ibutsu-pod script

- scripts/ibutsu-pod.sh
- Add ability to specify options in ibutsu-pod.sh
- Detect if script is running in the right directory
- Add options to the script for creating admin and project
- Add option to enable data persistence in postgres and redis
> Add data persistence to ibutsu-pod.sh script

- backend/ibutsu_server/controllers/admin/project_controller.py
- backend/ibutsu_server/controllers/admin/user_controller.py
- backend/ibutsu_server/db/models.py
- backend/ibutsu_server/openapi/openapi.yaml
- frontend/src/admin.js
- frontend/src/components/test-history.js
- frontend/src/pages/admin/project-edit.js
- frontend/src/pages/admin/project-list.js
- frontend/src/pages/admin/user-edit.js
- frontend/src/pages/admin/user-list.js
- frontend/src/utilities.js
- Add projects page in admin section
- Add editing of projects
- Add deleting of projects
- Always load all the tabs in test history (closes #311)
> Add project management for administrators

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Add basic user management
* Add project management for administrators
* Add a development Docker Compose file
* Update the Getting Started documentation
* Add data persistence to ibutsu-pod.sh script
* Ignore persistent data
> Release 2.1.0

- backend/docker/Dockerfile.flower
- backend/docker/Dockerfile.scheduler
- backend/docker/Dockerfile.worker
- backend/ibutsu_server/controllers/user_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/util/keycloak.py
- backend/ibutsu_server/util/oauth.py
- frontend/src/components/ibutsu-header.js
- frontend/src/components/user-dropdown.js
- frontend/src/pages/profile/tokens.js
- frontend/src/pages/profile/user.js
- frontend/src/profile.js
- Add user name edit capability to frontend
- Add update endpoint to backend
- Update the user name everywhere
- Fix a bug where 3rd party accounts were not regarded as active
- Refactor the profile pages into a separate directory
> Allow user's name to be edited

- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
> Release 2.1.2

- backend/ibutsu_server/tasks/__init__.py
I'm continuing chasing down errors in logs. I tried a few things but couldn't reproduce the error below. Therefore adding more logging to understand what's going on and what kind of data comes here. 
```
[2022-04-13 23:55:13,287: ERROR/MainProcess] Task handler raised error: AttributeError("'str' object has no attribute 'get'")
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.8/site-packages/billiard/pool.py", line 362, in workloop
result = (True, prepare_result(fun(*args, **kwargs)))
File "/opt/app-root/lib64/python3.8/site-packages/celery/app/trace.py", line 555, in _fast_trace_task
R, I, T, Rstr = tasks[task].__trace__(
File "/opt/app-root/lib64/python3.8/site-packages/celery/app/trace.py", line 499, in trace_task
I, _, _, _ = on_error(task_request, exc, uuid)
File …
```
> Check if the first argument passed to on_failure is a dict

- CHANGELOG.md
- frontend/src/dashboard.js
- Stop removing the dashboard if it is not in the list
- Update changelog
> Fix a bug with the dashboard

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Fix a bug with the dashboard
* Bump async from 2.6.3 to 2.6.4 in /frontend
> Release 2.1.4

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Fix version number in About dialog
* Add support for a dark theme
> Release 2.2.0

- backend/ibutsu_server/controllers/import_controller.py
- backend/ibutsu_server/openapi/openapi.yaml
- backend/ibutsu_server/tasks/importers.py
- Set the source via the API (see ibutsu/ibutsu-utils#6)
- Set the run_id property on the Import object (closes #308)
> Fix some issues in the import API

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Rename some methods to ensure unique operationIds
* Fix some issues in the import API
* Trim whitespace from filters (closes #342)
* Add the ability to add new projects
* add logging for lock
> Release 2.2.1

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Actually copy the source in the importers
* Fix the requestBody of the User endpoint in the OpenAPI spec
> Release 2.2.2

- README.md
- docs/source/examples/compose.rst
- docs/source/user-guide/running-server.rst
Corrected some typos and inconsistencies with regards to running
ibutsu containerized. README should now align with docs.
Resolves #360
> Modified documentation and README

- .github/workflows/tests.yaml
- backend/ibutsu_server/controllers/artifact_controller.py
- backend/ibutsu_server/db/models.py
- backend/ibutsu_server/tasks/importers.py
- frontend/src/run.js
- Update the archive importer code to handle run artifacts
- Make the importer less flakey
> Handle run artifacts in archive importer

- backend/ibutsu_server/controllers/result_controller.py
- backend/ibutsu_server/controllers/run_controller.py
> Fix error 500 when getting a non-existent result or run

- backend/ibutsu_server/__main__.py
- backend/ibutsu_server/tasks/importers.py
- scripts/ibutsu-pod.sh
- Handle both zipped and unzipped tar files but letting the tarfile module auto-detect compression
- Fix a minor issue in the podman script where Flask was only listening on 127.0.0.1 and thus not available outside the container
> Handle unzipped tar

- .gitignore
- docker-compose.dev.yml
- scripts/ibutsu-pod.sh
- Prevent backend and worker from interfering with each other's virtual environments
- Make the backend listen on the correct port in the Docker containers
- Fixes #362
> Update podman and Docker Compose configurations

- backend/celery_worker.sh
- backend/docker/Dockerfile.scheduler
- backend/docker/Dockerfile.worker
- backend/setup.py
We previously pinned Celery due to a bug in Kombu. Many moons have gone by since the advent of this bug and subsequent pin. Let us see if the bug still exists.
> Upgrade celery to handle a security issue, let's see if this works

- .github/workflows/api_tests.yaml
- backend/docker/Dockerfile.fuzz_testing
- backend/docker/start_fuzz_testing.sh
- docker-compose-fuzz.yml
This runs fuzzy API tests in GitHub actions.
The current results is
```
2022-08-01T09:14:47.9621732Z [36mapi-tests_1  |[0m =================================== SUMMARY ====================================
2022-08-01T09:14:47.9621865Z [36mapi-tests_1  |[0m 
2022-08-01T09:14:47.9622035Z [36mapi-tests_1  |[0m Performed checks:
2022-08-01T09:14:47.9622306Z [36mapi-tests_1  |[0m     not_a_server_error                    332 / 964 passed          FAILED 
```
> add schemathesis to actions

- backend/ibutsu_server/constants.py
- backend/ibutsu_server/controllers/widget_controller.py
- backend/ibutsu_server/widgets/accessibility_analysis.py
- backend/ibutsu_server/widgets/accessibility_dashboard_view.py
- frontend/src/components/view.js
- frontend/src/constants.js
- frontend/src/views/accessibilityanalysis.js
- frontend/src/views/accessibilitydashboard.js
- frontend/src/views/index.js
WIP
Accessibility dashboard work. Some of the accessibility files are just renamed copies of other files for now, so the line counts are deceptive.
> Accessibility dashboard

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json.backup
- frontend/recover.json
* Fix styling issues, plus minor cleanup
> Release 2.4.1

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Fix some issues in the admin controllers
> Release 2.4.2

- frontend/src/components/result.js
- frontend/src/run.js
> Add instructions for how to download an artifact

- .pre-commit-config.yaml
- backend/docker/start_fuzz_testing.sh
- backend/ibutsu_server/controllers/run_controller.py
- backend/ibutsu_server/controllers/widget_config_controller.py
- backend/ibutsu_server/db/models.py
- backend/ibutsu_server/encoder.py
- backend/ibutsu_server/models/base_model_.py
- backend/ibutsu_server/test/__init__.py
- backend/ibutsu_server/test/test_artifact_controller.py
- backend/ibutsu_server/test/test_group_controller.py
- backend/ibutsu_server/test/test_health_controller.py
- backend/ibutsu_server/test/test_login_controller.py
- backend/ibutsu_server/test/test_project_controller.py
- backend/ibutsu_server/test/test_report_controller.py
- backend/ibutsu_server/test/test_result_controller.py
- backend/ibutsu_server/test/test_run_controller.py
- backend/ibutsu_server/util/__init__.py
- backend/setup.py
- Validate UUIDs in all calls which take an ID
- Python upgrades from pyupgrade
> Add more UUID validation

- frontend/src/views/accessibilityanalysis.js
Added a filter to filter on the accessibility marker so the results list doesn't contain irrelevant results
> Added accessibility marker filter to remove irrelevant results

- backend/ibutsu_server/__init__.py
- backend/ibutsu_server/controllers/widget_config_controller.py
- backend/ibutsu_server/encoder.py
- backend/ibutsu_server/fixtures/__init__.py
- backend/ibutsu_server/test/__init__.py
- backend/ibutsu_server/test/test_widget_config_controller.py
- Fix #415 by adding support for users
- Fix #416 by handling missing widget configs correctly
- Add tests for widget config controller
- Fix some other minor issues
> Fix some issues in the widget config controller

- frontend/docker/Dockerfile.frontend
- frontend/docker/nginx.conf
- Also try to send the logs to stdout
> Try to fix some permissions issues in the container

- backend/ibutsu_server/db/models.py
- backend/ibutsu_server/db/upgrades.py
- frontend/src/dashboard.js
- frontend/src/pages/admin/project-edit.js
- frontend/src/utilities.js
> Provide a mechanism for a default dashboard per project

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
- podman_build.sh
* Add a default dashboard to a project, so that it appears when you select the project
* New filter-heatmap widget for making flexible heatmaps
* Migrate container images to use UBI8 minimal
* Add target ports to Routes
* Import the properties if set in JUnit XML
* Add missing email for superadmin
* Auto select fields for MetaFilter
* metadata.team filter in frontend
* Fix some issues in the widget config controller
> Release 2.5.0

- frontend/src/components/download-button.js
- frontend/src/components/index.js
- frontend/src/components/result.js
- frontend/src/report-builder.js
- frontend/src/run.js
- frontend/src/services/http.js
- frontend/src/utilities.js
- Fix the download buttons so that they actually download the artifact or report (closes #446 )
- Fix a couple other small issues (duplicate keys in lists, etc)
> Fix the download buttons

- backend/ibutsu_server/controllers/login_controller.py
- backend/ibutsu_server/util/keycloak.py
- ocp-templates/app-interface/backend.yaml
WARNING: Setting this to "false" is insecure! Use with extreme caution!
> Add the ability to disable SSL verification

- frontend/package.json
- frontend/src/index.css
- frontend/src/run.js
> Migrate to use the built-in TreeView component from PatternFly

- backend/ibutsu_server/test/test_widgets_result_summary.py
- backend/ibutsu_server/widgets/result_summary.py
Check if values are None and default to 0 if they are (fix #418)
> Check if values are None and default to 0 if they are (fix #418)

- frontend/src/index.css
- frontend/src/widgets/resultsummary.js
> Fix up font colour issues with the labels on various charts/widgets

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
> Release 2.5.3

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/setup.py
- frontend/package.json
* Fix expiry date validation by updating onChange handler
> Release 2.5.4

- docs/source/developer-guide/getting-started.rst
- frontend/src/widgets/importancecomponent.js
Fixed docs incorrectly referring to "script" directory instead of "scripts"
Changed importance widget to display percentages
> Small doc fixes and percentages for importance widget

- backend/docker/Dockerfile.backend
> split layers EVEN MORE

- CHANGELOG.md
- backend/ibutsu_server/openapi/openapi.yaml
- backend/pyproject.toml
- frontend/package.json
small fast releases for frontend bug fixes
> v2.5.10 release

- frontend/src/widgets/filterheatmap.js
include project ID in the URL
https://issues.redhat.com/browse/IQE-3165
> Fix filterheatmap URL composition for view

- frontend/src/dashboard.js
The state should not be updated by the get_default_dashboard function
> Fix bug with dashboard selection on back nav

- frontend/src/components/filtertable.js
> Convert FilterTable and MetaTable

- frontend/src/components/admin-page.js
- frontend/src/components/ibutsu-header.js
- frontend/src/components/ibutsu-page.js
- frontend/src/components/profile-page.js
- frontend/src/components/user-dropdown.js
Followup to https://github.com/ibutsu/ibutsu-server/pull/543
This PR aims to clean the code in UserDropdown component and deprecating the usage of the eventEmitter when possible
> Convert UserDropdown to Functional - Followup

- frontend/src/components/filtertable.js
Incorrect hook call in MetaFilter
> Fix bug, useState instead of useContext

- frontend/src/components/index.js
- frontend/src/components/new-dashboard-modal.js
- frontend/src/dashboard.js
> Convert NewDashboardModal

- frontend/src/app.js
- frontend/src/components/index.js
- frontend/src/components/view.js
> Convert custom view component

- frontend/src/components/index.js
- frontend/src/components/multivalueinput.js
- frontend/src/result-list.js
- frontend/src/run-list.js
- frontend/src/views/accessibilitydashboard.js
- frontend/src/views/jenkinsjob.js
Local testing passed with multi-value via `in` filter.
> Convert MultiValueInput

- frontend/src/components/index.js
- frontend/src/components/runsummary.js
- frontend/src/components/test-history.js
- frontend/src/run-list.js
- frontend/src/views/accessibilitydashboard.js
- frontend/src/views/jenkinsjob.js
Local testing looks good on run list table, result test history, and jenkins job view table
> Convert RunSummary

- frontend/src/admin.js
- frontend/src/pages/admin/project-edit.js
> Convert ProjectEdit

- frontend/src/components/test-history.js
Change time range from Dropdown to select so it's more visible what is selected currently + small refactor
> Update timerange test history

- frontend/src/components/add-token-modal.js
- frontend/src/pages/admin/project-list.js
- frontend/src/pages/profile/tokens.js
- frontend/src/profile.js
syntax updates to AddTokenModal
simplification of tokens page, remove pagination from URL params
> Convert UserTokens

- .pre-commit-config.yaml
- backend/ibutsu_server/constants.py
- backend/ibutsu_server/util/keycloak.py
- frontend/src/services/keycloak.js
* Added logic for different keycloak auth paths
* Modified code with suggestions
* Fixed linting issues
Cherry picked @wcater803 commit to main
> Added logic for different keycloak auth paths (#567)

- frontend/src/components/view.js
- frontend/src/views/accessibilityanalysis.js
- frontend/src/views/index.js
Given the scope and use of the widget, I'm going to commit what I've converted so far, but leave a TODO to continue this conversion later when this view and widget design is revisited.
> Convert AccessibilityAnalysisView

- frontend/src/components/view.js
- frontend/src/views/accessibilitydashboard.js
- frontend/src/views/index.js
Incomplete, but surface level conversion so it doesn't get left behind
> Convert Accessibility dashboard

- frontend/src/components/view.js
- frontend/src/views/compareruns.js
- frontend/src/views/index.js
- frontend/src/views/jenkinsjob.js
> Convert JenkinsJob View

- frontend/src/dashboard.js
- frontend/src/report-builder.js
- frontend/src/views/jenkinsjobanalysis.js
- frontend/src/widgets/genericarea.js
- frontend/src/widgets/index.js
Tested well locally on  build duration, overall heath tabs for jenkins job analysis, and in the dashboard widget.
> Convert GenericArea Widget

- frontend/src/dashboard.js
- frontend/src/views/jenkinsjobanalysis.js
- frontend/src/widgets/genericbar.js
- frontend/src/widgets/index.js
**Note**: branch's name should point to the IQE-3351
> Convert GenericBar Widget

- frontend/src/services/keycloak.js
There was a whitespace conflict here after cherry-picking the changes.  Just introducing a commit to format the props.
> Clean up branch conflict from keycloak changes

- frontend/src/dashboard.js
- frontend/src/views/jenkinsjob.js
- frontend/src/views/jenkinsjobanalysis.js
- frontend/src/widgets/filterheatmap.js
- frontend/src/widgets/genericarea.js
- frontend/src/widgets/index.js
Updated with comments from @LightOfHeaven1994, and retested locally on both Jenkins Job Analysis and Dashboard pages with a Jenkins heatmap widget.
Setting builds and counting skips as failures is working on my smaller dataset, all of these widgets need to be verified on larger datasets and this is where unit/functional tests for the frontend would really benefit the project.
> Convert filterheatmap

- frontend/package.json
- frontend/src/components/result.js
- frontend/src/run.js
- frontend/src/views/accessibilityanalysis.js
- frontend/yarn.lock
The JSON render was not aligning with the PF card edge, so I replaced it with PF CodeEditor to reduce the dependency footprint.
> Replace react-json with patternfly codeeditor

- backend/docker/Dockerfile.backend
- backend/docker/Dockerfile.flower
- backend/docker/Dockerfile.scheduler
- backend/docker/Dockerfile.worker
Making them consistent with Dockerfile.backend from #635
> Update pip install in backend dockerfile

- backend/ibutsu_server/db/models.py
> Cast the LH side of filter_by for UUIDs
