ibutsu/ibutsu-server

backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/src/result-list.js, frontend/src/run-list.js
This is attempting to address #6. 
This PR does the following: 
* Adds a timeout for the `mongo.results.count` query
* Adds a parameter `apply_max` (default: `False`), that limits the documents that are returned to a constant `MAX_DOCUMENTS` if `mongo.results.count` times out
* Sets `apply_max=True` in the FE when a filter is applied on the Results table
An unfortunate side effect of this approach is that sometimes the `count` takes a long time BUT there are actually _less_ documents than `MAX_DOCUMENTS`.
For example, say you are filtering by a component when you also have a project applied, the count will take a long time, but there might only be a few thousand records that match your filter. In the approach followed in this PR, query will return a `total_items` of `MAX_DOCUMENTS`. Of …
=> Limit the number of results we can display in the results table.

backend/ibutsu_server/tasks/reports.py, frontend/src/report-builder.js
Reports will sometimes run endlessly because they are not filtered. The server tries to poll ALL the result objects, meaning that the mongo container will run out of memory and crash. 
To avoid this, we should implement an upper limit on the amount of documents returned by reports, which I've set to 1 million in this PR (1e5 might be more reasonable though, thoughts @rsnyman?).
=> Limit documents for reports

frontend/src/components/decorators.js, frontend/src/components/result.js, frontend/src/views/jenkinsjob.js
Making the `build_number` and JIRA links open in a new tab. 
For linkify, I followed https://github.com/tasti/react-linkify/pull/51#issuecomment-585207861
=> Make links open in new tab

backend/ibutsu_server/tasks/reports.py, frontend/src/app.js, frontend/src/report-builder.js, frontend/src/views/jenkinsjob.js
* Fixing a compilation warning for not having `noopener` in the `rel` for links. 
* Limiting reports to 1e5 documents
The latter comes from some investigation locally, running (unfiltered) `html` reports with different values for the max documents. I limited my local mongo container to 1 GiB of memory and 1 CPU. 
| REPORT_MAX_DOCUMENTS | Runtime (s) | Approx File Size of Report | Report type |
| ------------- | ------------- | ------------- | ------------- |
| 100,000  | 80 | 250 MB | HTML |
| 200,000  | 200 | 500 MB | HTML |
| 1,000,000 | 800 | 2.5 GB | HTML |
| 100,000 | 20 | 21 MB | TEXT |
| 1,000,000 | 80 | 107 MB | TEXT |
Clearly 1e6 is too high for a realistic report. 1e5 seems okay but even then the file size is pretty high. We will need to start doing cleanup of report files if …
=> Fix warnings for links, limit reports to 1e6 documents

backend/ibutsu_server/constants.py, backend/ibutsu_server/widgets/jenkins_job_view.py
I noticed that on master, the JJV seems to be getting slower and slower to load. The reason for this is because the aggregation is looking through ALL the runs. 
Really, it just needs to be looking through the recent runs, so I applied a limit in the BE that makes it look through only the 8000 most recent runs (sorted according to `start_time`), which it uses to construct the JJV.
=> Apply a limit to the amount of runs from which we create the JJV

backend/ibutsu_server/constants.py, backend/ibutsu_server/widgets/jenkins_job_view.py, frontend/src/views/jenkinsjobanalysis.js, frontend/src/widgets/genericarea.js
Adding a switch to change the "Overall Health" chart from bar chart to area line chart. 
I couldn't get the tooltips to work, I think because of this bug: 
https://github.com/FormidableLabs/victory/issues/1608
So I added a prop to hide them. I don't know why they work in the duration chart but not this one. @rsnyman can you help with the styling of that switch? 
This PR also makes the widget load on tab select rather than loading them all at once.  
Screenshot:
**Note** this depends on #17, so we should review/merge that one before this one.
=> Add a switch to change overall health bar chart to area chart

backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
```
* Add a switch to change from overall health from bar to area chart
* Show active filters and make exception name clickable in failure classification table
* Apply a limit to the amount of runs from which we create the JJV
* Make failure classification table expandable, to aid in debugging
* Add a tooltip to the generic area chart
* Fix warnings for links, limit reports to 1e6 documents
* Make links open in a new tab
* Add link to submit upstream issue, make links open in new tab
* Limit documents returned by reports to a reasonable number
* Add trademark and file retention policy to About modal
* Add a link to the docs on the about modal
* Limit the number of results we can display in the results table.
* Made run-list component and env pills clickable for filtering
* Update the rtd …
```
=> Version 1.10.0

backend/ibutsu_server/tasks/reports.py
Should fix 
```
Traceback (most recent call last):
--
  | File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
  | R = retval = fun(*args, **kwargs)
  | File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
  | return self.run(*args, **kwargs)
  | File "/app/ibutsu_server/tasks/reports.py", line 416, in generate_html_report
  | report_dict = _make_dict(results)
  | File "/app/ibutsu_server/tasks/reports.py", line 209, in _make_dict
  | finish_time = result["start_time"] + result["duration"]
  | KeyError: 'start_time'
```
=> Check to make sure "start_time" exists when generating reports

backend/ibutsu_server/widgets/jenkins_heatmap.py
This is a follow up PR to #27 to make it so that the heatmap only shows builds which actually exist in the DB. It uses an aggregation similar to the one used in the JJV to pull the most recent `x` builds from the DB. In so doing it removes the need for the `build_number` arg. 
Now the heatmap should always show the number of builds specified in `Set builds to:` parameter. @rsnyman can you do a bit of local testing here to make sure I didn't break anything?
Showing a similar image to the one shown in #27, you can see that the builds go all the way back to `284` now:
=> [Heatmap] Follow up to #27

backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Fix styling of count skips on Jenkins Job Analysis page (#29)
* [Heatmap] Sort builds by start_time, not the string build_number
* [Heatmap] Use an aggregation to get the correct number of jobs that exist in the DB
* [Heatmap] Don't show columns in which all the plugins failed
* Add link to JIRA issues.redhat.com
* Convert failure classification table into its own component
* Expose the count_skips parameter in the UI (#24)
* Check to make sure "start_time" exists
=> Version 1.10.1

backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/test/test_run_controller.py
This should fix https://issues.redhat.com/browse/IBUTSU-28. 
Since results are updated [asynchronously](https://github.com/ibutsu/pytest-ibutsu/blob/master/pytest_ibutsu.py#L489), occasionally I think that a result will update AFTER the run has been updated for the last time. This can cause the pass,fail,etc. values for the run to be inaccurate. 
Waiting 5 s before updating the run should give time for all the results to update before updating the run.
=> Use apply_async and countdown=5 when updating run

backend/ibutsu_server/tasks/importers.py, backend/ibutsu_server/tasks/queues.py, backend/ibutsu_server/tasks/reports.py, backend/ibutsu_server/tasks/runs.py
We've been having issues with `html` reports failing and retrying indefinitely. This PR fixes up a couple of the exceptions that we've been seeing with those tasks. 
In addition, this PR changes the default `max_retries` for the task to 3 (which is celery's [default](https://docs.celeryproject.org/en/stable/userguide/tasks.html#Task.max_retries)). 
Going forward, I think we should specify tasks that should retry more than 3 times specifically (e.g. for the `update_run` task, I set `max_retries` to 1000). I can't think of a good reason why we should retry reports and the other tasks more than 3 times. @rsnyman is there a historical reason why we've defaulted to 1000 retries for all tasks?
=> Default to 3 retries for tasks, fix some small report bugs

backend/ibutsu_server/db/base.py, backend/ibutsu_server/filters.py, backend/ibutsu_server/widgets/run_aggregator.py
Can be tested by running, e.g. 
```
curl -X GET "http://localhost:8080/api/widget/run-aggregator?weeks=2&group_field=metadata.component" -H "accept: application/json"
```
Response (from my DB):
```json
{
"error": {
"platform_ui": 0,
"rbac_frontend": 0
},
"failed": {
"platform_ui": 29,
"rbac_frontend": 21
},
"passed": {
"platform_ui": 65,
"rbac_frontend": 72
},
"skipped": {
"platform_ui": 6,
"rbac_frontend": 7
}
}
```
=> Convert the run aggregator widget to PSQL

backend/ibutsu_server/filters.py, backend/ibutsu_server/widgets/result_aggregator.py
```
curl -X GET "http://localhost:8080/api/widget/result-aggregator?days=10&group_field=result" -H "accept: application/json"
```
Output:
```json
[
{
"_id": "passed",
"count": 161
},
{
"_id": "skipped",
"count": 20
},
{
"_id": "failed",
"count": 10
},
{
"_id": "error",
"count": 7
},
{
"_id": "xfailed",
"count": 1
}
]
```
Note that I didn't make use of `_get_min_count`, if this widget gets used, we can enable it then.
=> Convert result aggregator widget to postgres

backend/ibutsu_server/filters.py, backend/ibutsu_server/widgets/jenkins_heatmap.py, backend/ibutsu_server/widgets/result_aggregator.py, backend/ibutsu_server/widgets/result_summary.py, backend/ibutsu_server/widgets/run_aggregator.py
Need to check performance when we migrate prod data to postgres, particularly for getting the distinct builds. But all original functionality of the Jenkins heatmap widget is intact. 
I also added some helper functions in `filters.py` as I noticed I was repeating code a lot across the widgets.
=> Convert the jenkins heatmap to postgres

backend/ibutsu_server/controllers/widget_config_controller.py, backend/ibutsu_server/widgets/jenkins_job_analysis.py, backend/ibutsu_server/widgets/jenkins_job_view.py, frontend/src/views/jenkinsjob.js
Needs performance testing, but functionality is intact. 
~Depends on #39~
* A small change to fix a bug in the Jenkins Job view FE (multiple filters weren't applied correctly)
* Fix filtering of widgets
With this PR, the widget conversion to PSQL is complete.
=> Convert jenkins job view to postgres

.pre-commit-config.yaml, backend/ibutsu_server/controllers/artifact_controller.py, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/controllers/widget_config_controller.py, backend/ibutsu_server/db/models.py, backend/ibutsu_server/filters.py, backend/ibutsu_server/scripts/mongo2postgres.py, backend/ibutsu_server/widgets/jenkins_heatmap.py, frontend/src/app.js, frontend/src/dashboard.js, frontend/src/result-list.js, frontend/src/run-list.js, frontend/src/run.js
Leaving as a draft until we figure out the indexes we need.
Some things I considered: 
* Only migrating run, result, and artifact files from the most recent 3 months (determined by the newest record in the MongoDB)
- This will keep our initial DB size small and also vastly reduce the time to run the migration script
- If we were to migrate everything it would take ~20 hrs I believe
* Adding a `upload_date` field to the artifact model
* Only migrating artifacts, we don't have many/any recent reports, so I thought it best to just migrate artifacts
* Not migrating any imports
I got many of the column indexes, but there are still the JSON indexes to consider. 
@rsnyman I'd figure I make this part of ibutsu-server so that we can use the models' `from_dict` method that we have defined in the db …
=> Update the migration script to work with new psql db

backend/ibutsu_server/widgets/jenkins_heatmap.py, backend/setup.py
There are some UUID's populating the `metadata.run` field of some results in production ibutsu.
=> Hotfix for jenkins heatmap issue

.pre-commit-config.yaml, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/db/util.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/util/count.py, frontend/src/result-list.js, frontend/src/run-list.js
Various utility functions to aid in counting large tables.
This makes use of (a variant on) the count estimate function described here: 
https://wiki.postgresql.org/wiki/Count_estimate
Via implementing an `Explain` that can be used to `Explain` general SQLAlchemy queries, described here: http://www.wmmi.net/documents/SQLAlchemy.pdf
=> Estimate counts in large tables by using rows returned from Explain

backend/ibutsu_server/constants.py, backend/ibutsu_server/widgets/jenkins_job_analysis.py
I added this param manually on prod, so the issue is fixed there, but best to keep the default value correct as well. 
On the analysis page, this was causing a bunch of n/a columns to show up. 
Also adding a row limit for fetching the bar/line charts on the Jenkins Job analysis page
=> Group by component not metadata.component by default

backend/ibutsu_server/tasks/runs.py, frontend/src/components/result.js
@jjaquish's xfail/xpass work was mostly ported over in the migration, but there were some small things that needed to be remedied in order for it to work properly. 
Note:
* widgets need to consider xpass/xfail in percentage calculations
* the results tree also needs to consider xpass/xfail in the pass percentage calculation
When used with Parthvi's iqe-core updates:
=> Updates to support xfail in Ibutsu

backend/ibutsu_server/controllers/import_controller.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/tasks/importers.py, backend/ibutsu_server/test/__init__.py, backend/ibutsu_server/test/res/empty-testsuite.xml, backend/ibutsu_server/test/test_tasks.py
- Fix issue #75 
- Fix task tests
=> Handle empty testsuites in the XML importer

backend/ibutsu_server/widgets/jenkins_heatmap.py
This should get rid of older builds showing up in the heatmap shortly after the Jenkins migration. 
Also filtering by `min_start_time` so that we don't get builds that are "old".
Note: we should potentially add `build_url` as a parameter in the heatmap to avoid this issue altogether. But this will be a larger effort as we'll need an index on that field.
=> Sort recent builds by start_time rather than build_number

backend/ibutsu_server/filters.py
Fixes
```
File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-server/backend/.ibutsu-env/lib/python3.8/site-packages/connexion/decorators/validation.py", line 384, in wrapper
return function(request)
File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-server/backend/.ibutsu-env/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
return function(**kwargs)
File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-server/backend/ibutsu_server/controllers/run_controller.py", line 58, in get_run_list
filter_clause = convert_filter(filter_string, Run)
File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-server/backend/ibutsu_server/filters.py", line 80, in convert_filter
column = string_to_column(field, model)
File "/home/jdupuy/iqe/iqe-repos/ibutsu/ibutsu-server/backend/ibutsu_server/filt …
```
=> Allow filtering by JSON run summary fields

backend/ibutsu_server/tasks/importers.py, frontend/src/utilities.js
Meant to address #93 
* Use `classname` as a backup for `fspath`/`file` if `file` isn't in the XML file
* If both fail, handle `null` `fspath` values in the FE `cleanPath` method
=> Fix result tree page crash on junit imported run

backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/widgets/jenkins_heatmap.py, frontend/src/widgets/jenkinsheatmap.js
* Adding a `/runs/bulk-update` endpoint, which allows you to update multiple runs at a time. It takes filter like the get runs endpoint takes. 
e.g. by passing 
```json,
{
"metadata": {
"annotations": [
{
"description": "Optional description",
"name": "deploymentAnnotation",
"value": "Application was deployed at <timestamp>"
},
{
"description": "Optional description",
"name": "otherAnnotation",
"value": "A different type of annotation"
}
]
}
}
```
Example curl request to update the most recent stage-test-suite run on the foreman_rh_cloud plugin:
```
curl -X POST "<ibutsu-api-url>/api/runs/bulk-update?filter=metadata.jenkins.job_name%3Dstage-test-suite&filter=component%3Dforeman_rh_cloud&pageSize=1" -H "accept: application/json" -H "Content-Type: application/json" -d …
```
=> Allow for updating the metadata of multiple runs at a time and display annotations in heatmap

backend/ibutsu_server/controllers/dashboard_controller.py, backend/ibutsu_server/openapi/openapi.yaml, frontend/src/app.css, frontend/src/dashboard.js, frontend/src/utilities.js
- Add a dropdown to select dashboard
- Update dashboard with widgets based on selected dashboard
- Add delete to the dashboard API
Please note:
- When the project is changed, there's some logic to check if the selected dashboard is part of the project
- The delete API method will unset the dashboard id on widget configs, but should we rather delete the widget configs?
=> Dashboard frontend

backend/ibutsu_server/constants.py, backend/ibutsu_server/widgets/jenkins_heatmap.py, backend/ibutsu_server/widgets/result_aggregator.py, backend/ibutsu_server/widgets/result_summary.py, backend/ibutsu_server/widgets/run_aggregator.py
This PR allows users to specify custom filters for a few widgets, so that they can filter on specific metadata. 
e.g. filtering by `platform-experience` tag
=> Add custom filters for some widgets

backend/ibutsu_server/constants.py, frontend/src/components/new-widget-wizard.js
Depends on #105 
* Adds default values to existing widget params, where appropriate
* Adds `required` to existing widget params, so users can tell where params are required. 
Note: ~~it doesn't disable the "Next" button like it does for the title.~~ I got this working but please check if I could do this in a better way @rsnyman.
=> Add default, required key value pairs to widget params

frontend/src/components/delete-modal.js, frontend/src/components/index.js, frontend/src/components/widget-components.js, frontend/src/dashboard.js, frontend/src/widgets/genericarea.js, frontend/src/widgets/genericbar.js, frontend/src/widgets/jenkinsheatmap.js, frontend/src/widgets/resultaggregator.js, frontend/src/widgets/resultsummary.js
* Re-name `DeleteDashboardModal` -> `DeleteModal` so it can be used for widgets
* Add a "X" button to the widget header (only appears if `onDeleteClick` prop is passed)
* On widget delete the widgets are reloaded
=> Add a button for deleting a single widget from a dashboard

ibutsu-server-openshift.yaml
Backups were failing to be removed due to some invalid arguments being piped to `rm` through `xargs`. 
This issue didn't show up until we had enough backups in order for this to trigger. We just want the file name to pipe to `rm` through `xargs` not the permissions, etc. of the file.
=> Just use "ls" rather than "ls -ltr"

backend/ibutsu_server/tasks/__init__.py, backend/ibutsu_server/tasks/db.py
* Prune runs, results on weekly basis
* Runs older than 12 months will be removed 
* Results older than 6 months will be removed
* Fixing a bug that was deleting artifact files prematurely
=> Add in tasks to prune old runs and results from the DB

backend/ibutsu_server/tasks/reports.py
Thanks @mshriver for reporting the issue! 
Fixes this exception that shows up whenever reports are filtered:
```
File "/app/ibutsu_server/tasks/reports.py", line 132, in _get_results
query = _build_query(report)
File "/app/ibutsu_server/tasks/reports.py", line 120, in _build_query
filter_clause = convert_filter(Result, report_filter.strip())
File "/app/ibutsu_server/filters.py", line 50, in convert_filter
match = FILTER_RE.match(filter_string)
TypeError: expected string or bytes-like object
```
=> Fix filters on reports

backend/ibutsu_server/constants.py, backend/ibutsu_server/util/count.py
* actually count when we are filtering on small subset of results/runs 
This will fix pagination issues when users are filtering on a small subset of items and the count estimate is WAY off.
=> Better count estimates

backend/ibutsu_server/tasks/importers.py, backend/ibutsu_server/tasks/runs.py, backend/ibutsu_server/test/test_tasks.py, frontend/src/run.js
* Remove some of the duplicated logic in the pytest-plugin
* Use the number of collected tests in the frontend
Requires https://github.com/ibutsu/pytest-ibutsu/pull/17
@rsnyman Will this break the imports? I'm debating whether we can get rid of the loop over the results in the update_run task altogether, all we need is 1 result to copy the metadata/columns over.
Note the pass percentages are still determined from `run.summary.tests`. Meant to address https://github.com/ibutsu/pytest-ibutsu/issues/13
=> Output number of collected tests

backend/ibutsu_server/db/models.py
This was causing issues with the new API client in the instance where `data = None`, we should still convert it to `metadata` in that instance.
=> Use 'in' rather than dict.get()

backend/setup.py
SqlAlchemy 1.4.3 breaks `ibutsu-server`.
We will have to be careful with this upgrade. In particular, this import is no longer available:
```
from sqlalchemy.sql.expression import _literal_as_text
```
=> Pin SqlAlchemy to 1.3.23

.gitignore, .pre-commit-config.yaml, backend/ibutsu_server/constants.py, backend/ibutsu_server/filters.py, backend/ibutsu_server/tasks/__init__.py, backend/ibutsu_server/tasks/db.py, backend/ibutsu_server/tasks/reports.py, backend/ibutsu_server/tasks/results.py, backend/ibutsu_server/tasks/runs.py, backend/ibutsu_server/test/test_artifact_controller.py, backend/ibutsu_server/test/test_tasks.py, backend/ibutsu_server/widgets/jenkins_heatmap.py, backend/ibutsu_server/widgets/jenkins_job_view.py
Address #167
* Update pre-commit
* Add in a periodic task (runs every 15 minutes) to look at recent runs and sync `summary.tests` with the actual number of results
Change the way the `update_run` task works (basically reverting some of the changes made in #147), although this has redundancy with the pytest-ibutsu plugin (summary is being computed again), this is the cleanest way to make sure the runs are synced with the results.
=> Update pre-commit; add in task for syncing aborted runs

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Change 204 to 206
* Add an API endpoint to check the status of a task
* Small changes to OCP templates
* Update pre-commit; add in task for syncing aborted runs
* Update the Python dependencies (#169)
* Fix division by 0 in the jenkins heatmap
=> Release 1.13.2

backend/ibutsu_server/controllers/task_controller.py, backend/ibutsu_server/tasks/runs.py
* Tasks which had no `return` statement are hitting an error at that `response.update` line
* Also check that `result.duration` is not `None` before adding it to `run.duration` in the update_run task
This will fix the error:
```
File "/app/ibutsu_server/tasks/runs.py", line 77, in update_run
run.duration += result.duration
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
```
=> Handle 'None' result in the task controller

backend/config.py, backend/ibutsu_server/controllers/run_controller.py, frontend/src/result-list.js
* fix the `bulk_update` endpoint, this was broken by `query` task
* make it so that the fe doesn't request a number of runs > 500
* change the number of gunicorn workers in the backend pod to 1, this way we can let OCP handle the auto-scaling
=> Small bug fixes

Dockerfile, backend/.dockerignore, backend/docker/Dockerfile.backend, backend/docker/Dockerfile.flower, backend/docker/Dockerfile.monitor, docker-compose.yml, frontend/.dockerignore, frontend/docker/Dockerfile.frontend, ocp-templates/ibutsu-server-openshift.yaml
* Update flower/monitor with proper changes for the new image
* Change the frontend and backend container images to the appropriate s2i scripts
- https://github.com/sclorg/s2i-python-container/tree/master/3.8 for the backend
- https://github.com/sclorg/s2i-nodejs-container/tree/master/14 for the frontend
* Remove root `Dockerfile` that is no longer used
* Fix/update docker-compose (I am not very familiar with docker-compose but I wasn't able to get it working without `network_mode: host`), anyways, I think https://github.com/ibutsu/ibutsu-server/pull/191 using `podman pods` is a much better strategy
The changes to the dockerfiles for the frontend/backend are meant to mimic the s2i strategy we use in OCP, for more information, see the README's at the `sclorg` links above.
=> Small changes to dockerfiles

.gitignore, scripts/ibutsu-pod.sh
Basically this will:
* Create a podman pod called "ibutsu"
* Deploy redis, postgres containers into the pod
* Mount local files into backend/frontend/worker pods and start each of them
* Note this must be run from the root directory of the repository
Sample output:
```console
(.ibutsu-env) [jdupuy@localhost ibutsu-server]$ ./scripts/ibutsu-pod.sh 
Creating ibutsu pod...
4050405df87c23982bf96d045fb68e1d2dbb3706141c3c80ac71f7ff62fa1033
Adding postgres to the pod...
297fa13d76a85a24730a585e315177c1d888e520838bbcd8824cbe1ca9c9c804
Adding redis to the pod...
1de887ba425e0154073d4db220ebf499fc8414ae7bc95959a8f8823f8b6026ab
Adding backend to the pod...
76f022a72480734c69acd34eb77aa78a45a96c5649b33a8eca603da48a57bf2c
Waiting for backend to respond
..
Adding celery worker to the pod... …
```
=> Add a script to start Ibutsu in a podman pod for local development

frontend/docker/Dockerfile.frontend, frontend/docker/start-frontend.sh, frontend/public/index.html, frontend/public/settings.js, frontend/src/settings.js
Address https://github.com/ibutsu/ibutsu-server/issues/192 by:
- creating a `public/settings.js` file that is loaded before react
- adding a `start-frontend.js` that overwrites the `public/settings.js` file at container runtime
- changing `src/settings.js` to be assigned to window.settings
Depends on #188
=> Frontend env vars at container runtime

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Release 1.13.3
* Add a script to build a settings file at container runtime
* Small changes to dockerfiles
* Add a script to start ibutsu in a podman pod
* Sync aborted runs from the last 3 hrs
* Small bugs fixes
* Also fix possibility that duration is None is update_run task
* Handle 'None' results in the task controller
* Change the user when copying over the application
* Use Ubi8 images
* Build worker, schedule too
* Add a build image stage in tests.yaml
* remove travis.yml
* Change from travis to gh action
This release has a few bug fixes, but it's mostly just deployment/ci related things. I'd like to use this release to test out the build triggers in https://quay.io/organization/ibutsu
=> Release 1.13.3

backend/ibutsu_server/controllers/project_controller.py, frontend/package.json, frontend/yarn.lock
Allow users to be added to projects by the API:
- This is done by sending a list of usernames (emails) in the request body, e.g.
```json
{
"users": ["jdupuy@redhat.com", "jdoe@blah.com", "jdeer@redhat.com"]
}
```
If the user does not exist in the DB, they won't be added. If the user is already in the project, they won't be added. 
Users can only update projects under the following conditions:
- They are a project owner
- They are a super admin
Depends on #237 
Addresses #236
=> Support adding users to projects via the API

backend/ibutsu_server/__init__.py, backend/ibutsu_server/db/util.py, ocp-templates/prod/backend.yaml, ocp-templates/stage/backend.yaml
Create a super admin given environment variables. 
I built this image locally and tagged it as `quay.io/ibutsu/backend:add-superadmin-startup` so we can test it on the staging server.
=> Add ability to create superadmin user on startup

backend/ibutsu_server/__init__.py
Follow up from #248, in the stage env I tried to start the backend with a DB replicated from the prod DB. The container fails to startup with an error in the `add_superadmin` script. 
This is because the database has not yet been updated to include the columns for Users table. We need to upgrade before trying to add the superadmin.
=> Add superadmin user after upgrading db

.gitignore, frontend/src/components/classify-failures.js, frontend/src/components/filtertable.js, frontend/src/components/index.js, frontend/src/constants.js, frontend/src/utilities.js
Alternative to #221 that is more generic. Similar to the filters used on
the run/results page, and could be an abstract replacement for their
current filters.
=> Implement MetaFilter with separate field and value

backend/ibutsu_server/controllers/login_controller.py, backend/ibutsu_server/test/__init__.py, backend/ibutsu_server/test/test_login_controller.py, frontend/src/login.js
- Add a config option for disabling basic auth - `USER_LOGIN_ENABLED`
- Minor UX enhancement for showing the spinner when keycloak is used
- Stopping the spinner when we get back a 401 from the backend.
=> Add a way to disable basic auth for non-superadmins

backend/ibutsu_server/__init__.py, frontend/src/components/classify-failures.js, frontend/src/components/result.js, frontend/src/components/runsummary.js, frontend/src/components/test-history.js, frontend/src/run-list.js, frontend/src/utilities.js
Adding a test result history tab to the `ResultView`. This page contains the following:
- Dropdown to select a date range (1 Week, 2 Weeks, 1 Month, 2 Months, 3 Months, 5 Months) from which to view the test's history
- Quick filter to view only failed/error results
- Small summary of passed/failed/error given the date range (note this ignores the quick filter for only viewing failed/error results)
- Table of historical results
It looks like this:
It is also possible to view this page within the classify-failures page of a run:
I also introduce lazy-loading of the `ResultView` on table expansion for both this page and the `classify-failures` page. It's largely based on: https://github.com/patternfly/patternfly-react/issues/1450
Especially for failed tests, one potential enhancement would …
=> Add test history tab to Result page

frontend/src/login.js
- Hide/show username/password fields
- Hide/show registration and forgot password links
- Change login message depending on user login status
=> Hide username/password related components when user login is disabled

frontend/src/components/classify-failures.js, frontend/src/components/result.js, frontend/src/components/test-history.js
- Move the summary down where table filters would be
- Add a link to the most recent passed result
- Default to open the "test-history" tab on the classify-failures page
- Load the summary before the table
New look:
=> Small improvements test history

backend/ibutsu_server/tasks/importers.py, backend/ibutsu_server/test/res/combined.xml, backend/ibutsu_server/test/test_importers.py
Looks like the run dict exposes the "metadata" property instead of data. Fixing that to properly import tests results. 
Fixes: https://github.com/ibutsu/ibutsu-server/issues/291
=> Fix metadata reading during test import

README.md, scripts/ibutsu-pod.sh
I was unable to start the project without the settings.yaml symlink in `backend/`. I'm adding that step to setup and also adding .com to the login credentials for clarity.
=> Adding project setup fixes to documentation

frontend/src/components/test-history.js
For many projects (e.g. SatQE), `env` will be null as it's kind of an IQE specific thing. 
On the test history page we shouldn't default to filtering on a `null` field.
=> Only filter on env if an env is not null

ocp-templates/app-interface/backend.yaml, ocp-templates/prod/backend.yaml, ocp-templates/stage/backend.yaml
=> Add JWT secret to template files

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Clear projects and dashboards when logging out. Fixes #295
* fix metadata reading during test import
* Bump url-parse from 1.5.3 to 1.5.10 in /frontend
* Bump follow-redirects from 1.14.7 to 1.14.8 in /frontend
* newbie fixes
* Bump nanoid from 3.1.23 to 3.2.0 in /frontend
* Only filter on env if an env is not null
* Add some logging and a URL check (#284)
* Bump follow-redirects from 1.14.1 to 1.14.7 in /frontend
* Add JWT secret to template files
=> Release 2.0.1

backend/ibutsu_server/controllers/run_controller.py
- Attaching the project to the run immediately may be causing an auto-flush, which results in an exception when trying to commit the run later
=> Fix a potential auto-flush issue when a run is created.

backend/ibutsu_server/tasks/importers.py, backend/ibutsu_server/test/res/collection.xml, backend/ibutsu_server/test/test_importers.py
Sometimes test cases in the junit report do not have the "time" attribute. In that case, the import will fail to convert None to float. This PR fixes this issue by defaulting the time attribute to 0.
=> Allow to import tests cases without time attr

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Add an ellipsis to the heatmap labels
* Move admin creation into environment variables
* Fix ibutsu-pod script
* Allow to import tests cases without time attr
=> Release 2.0.3

README.md, docker-compose.dev.yml
I also pinned python image to 3.9 because I was getting
```
ImportError: cannot import name 'Mapping' from 'collections'
```
This error happens in python 3.10.
=> fix docker-compose command in README

backend/ibutsu_server/controllers/result_controller.py
This error is found in logs
```
[2022-04-13 10:47:30,359] ERROR in app: Exception on /api/result/f06312d1-43f7-480c-b84d-892103eb6803 [PUT]
Traceback (most recent call last):
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/app-root/lib64/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/app-root/lib64/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File …
```
=> fix AttributeError: 'NoneType' object has no attribute 'project'

frontend/src/constants.js
New `metadata.endpoint` filter in Ibutsu Frontend to filter the tests based on API, UI and CLI endpoints on any product.
=> New endpoint filter in frontend to filter the tests

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Check if the first argument passed to on_failure is a dict
* new endpoint filter for frontend
* fix AttributeError: 'NoneType' object has no attribute 'project'
* fix docker-compose command in README
=> Release 2.1.3

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Runs can now display artifacts
* Update the archive importer code to handle run artifacts (closes #364)
* Make archive importer less flakey 
* Fix fetching the artifacts from the frontend 
* Remove Python 3.7 from the version matrix, add 3.10
* Modified documentation and README
* Make project mandatory
* Fix GET non-existent runs and results returning 500 (fixes #366)
=> Release 2.2.3

backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/widget_config_controller.py, backend/ibutsu_server/controllers/widget_controller.py, backend/ibutsu_server/filters.py, backend/ibutsu_server/test/test_widget_controller.py, backend/ibutsu_server/widgets/compare_runs_view.py, frontend/src/components/classify-failures.js, frontend/src/components/filtertable.js, frontend/src/components/result.js, frontend/src/components/test-history.js, frontend/src/components/view.js, frontend/src/constants.js, frontend/src/utilities.js, frontend/src/views/compareruns.js, frontend/src/views/index.js
This feature adds the ability for admins to define a new view for comparing runs. At the moment users can use MetaFilter and FilterTable to select the different types of results they would like to compare. They will then retrieve a list of tests where the results are not the same. I have a video demo I can share if you would like to see current functionality while this is being reviewed.
Some relevant notes:
- I made an update to MetaFilter so that the filters are shown within the MetaFilter render function instead of the FilterTable's render
- I also gave MetaFilter a property called `id` that takes a number so that you can define multiple filters for your FilterTable
- Adjusted ResultView to allow optional showing of artifacts (logs)
- Adjusted ResultView and TestHistory to take a …
=> Add Compare Runs view

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json, scripts/make-release.sh
* Bump terser from 4.8.0 to 4.8.1 in /frontend
* comparison view
* restore usage of _orig_func instead of __wrapped__
* get_app returns a flask app instead of connexion
* ensure db url parsing handles test configuration
* drop nose dependency
* remove python 3.7 and add the modern ones
* restore env var prefixes in podman pod yaml
* split ibutsu pod config into configmaps
* create flask based entrypoints and enable podman play usage
* summaries computation: allow any custom summary
* fix extraction of celery wrappers
* steamline configuration setup
* make flask >2 the minimum
* default settings: use pod name instead of localhost for celery
* use non-interactive non-terminal containers for ibutsu_pod.sh
* add manual/blocked states to api spec
=> Release 2.3.0

backend/ibutsu_server/controllers/admin/project_controller.py, backend/ibutsu_server/controllers/group_controller.py, backend/ibutsu_server/openapi/openapi.yaml
This is fixing some of the reported errors.
1. Handle the case for creating a project with the same project id
2. Handle the case for creating a project with the group id that doesn't exist. Creating a project without group id is permitted by the openapi schema.
3. Fix negative offset. Set it to 0 in case it is negative.
4. Validate id is in UUID format.
5. Add missing DB commit for creating a group.
6. Add `format: uuid` for all ids in UUID format to the openapi schema. It doesn't seem to affect validation but I think it's a good practice.
7. Fix description of the filename parameter `description: ID of pet to update` to the `description: name of the file`
8. Add minimum to the `PageSize` in openapi. It provides automatic validation. Before it was possible to request page_size of 0, …
=> fix api errors found in fuzzy testing, part 1

backend/ibutsu_server/tasks/importers.py, frontend/src/components/classify-failures.js, frontend/src/constants.js
user_properties is promoted into metadata on results from the client, imported results should get the same treatment.
Tested with an archive with user_properties, need to test with one without as well.
This is not addressing junit import, which would have to pull the `properties` elements when trying to parse metadata.
=> Promote user_properties on archive import

backend/docker/start_fuzz_testing.sh, backend/ibutsu_server/controllers/admin/project_controller.py, backend/ibutsu_server/controllers/admin/user_controller.py, backend/ibutsu_server/controllers/artifact_controller.py, backend/ibutsu_server/controllers/dashboard_controller.py, backend/ibutsu_server/controllers/group_controller.py, backend/ibutsu_server/controllers/health_controller.py, backend/ibutsu_server/controllers/import_controller.py, backend/ibutsu_server/controllers/login_controller.py, backend/ibutsu_server/controllers/project_controller.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/test/__init__.py, backend/ibutsu_server/test/test_group_controller.py, backend/ibutsu_server/test/test_health_controller.py, backend/ibutsu_server/test/test_project_controller.py, backend/ibutsu_server/util/login.py
This is a second batch of fixing API errors found in fuzzy testing.
It includes:
1. Modify the test command - exclude `/api/health` because it returns 5xx error codes
2. Validate UUID in more places
3. Check if the object already exists in various places
4. Replace error code from `500` to `503` in database health check. It is more specific.
5. Fix another typo in openapi schema `description: ID of pet to update`
6. Add `validate_activation_code` function to validate the activation code
=> fix api errors found in fuzzy testing, part 2

backend/ibutsu_server/controllers/report_controller.py, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/test/test_result_controller.py, backend/ibutsu_server/test/test_run_controller.py
1. Validate more UUIDs
2. Validate if the result already exists
3. Don’t try to add project_id to the result if the project was not found
4. Make report type required in the schema
=> fix api errors found in fuzzy testing, part 3

backend/ibutsu_server/controllers/admin/project_controller.py, backend/ibutsu_server/controllers/admin/user_controller.py, backend/ibutsu_server/controllers/artifact_controller.py, backend/ibutsu_server/controllers/dashboard_controller.py, backend/ibutsu_server/controllers/group_controller.py, backend/ibutsu_server/controllers/project_controller.py, backend/ibutsu_server/controllers/report_controller.py, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/controllers/user_controller.py, backend/ibutsu_server/controllers/widget_config_controller.py, backend/ibutsu_server/db/models.py, backend/ibutsu_server/openapi/openapi.yaml, backend/ibutsu_server/test/test_login_controller.py, backend/ibutsu_server/test/test_project_controller.py, backend/ibutsu_server/util/query.py
This is a 4th batch of fixing API errors found in fuzzy testing.
It includes:
1. Fixing offset in all places
2. Add some more uuid validation
3. Fix `from_dict` method, so it doesn’t throw an error in case of empty keys (e.g. empty strings)
4. Add missing email format validation to openapi schema
=> fix api errors found in fuzzy testing, part 4

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Fix various API errors found in fuzzy testing
* Add/update the accessibility dashboard
* Promote user_properties on archive import
* Add schemathesis to actions
* Upgrade Celery to the latest version
* Update podman and Docker Compose configurations
* Flask listens on 127.0.0.1 by default, add the ability to specify it for podman
* Drop the tarfile open mode to autodetect compression
=> Release 2.4.0

frontend/src/components/test-history.js
Solving https://github.com/ibutsu/ibutsu-server/issues/408.
As a temporary improvement (not entirely fixed yet) I added component to the filter for test history, so that the history at least only shows results within the same component and the same test name. However it is still possible to have two different tests that have the same name and same component returned in the test history result.
=> Fixing test history bug

frontend/src/components/edit-widget-modal.js, frontend/src/components/index.js, frontend/src/components/widget-components.js, frontend/src/dashboard.js, frontend/src/widgets/genericarea.js, frontend/src/widgets/genericbar.js, frontend/src/widgets/jenkinsheatmap.js, frontend/src/widgets/resultaggregator.js, frontend/src/widgets/resultsummary.js
Solving https://github.com/ibutsu/ibutsu-server/issues/389
This PR adds a button to each widget for editing the widget. When the button is clicked a Modal pops up with the fields already filled out with the widgets details. Users can then make changes and click save. Note: All edits will shown on save except for the widget's title. For some reason it only updates on a full page refresh. I can look into this more. 
Everything else is working correctly, but I have this error in the console that I can't track down in the code.
=> Adding ability to edit dashboard widgets

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Added accessibility marker filter to remove irrelevant results
* Adding ability to edit dashboard widgets
* Fixing test history bug
* Add more UUID validation
* Updated precommit
* Migration to component testing using Cypress
* Fixed url for flake8 hook
* Fixing Jenkins Bar and Line charts
* Change the homemade copy-paste component to the one from PatternFly
* Add instructions for how to download an artifact
* Adding days and project_id to compare-runs-data calls
=> Release 2.4.3

frontend/src/constants.js
New filter `metadata.team` to filter the tests, create dashboards etc based on Team metadata.
=> metadata.team filter in frontend

backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/widget_controller.py, backend/ibutsu_server/widgets/filter_heatmap.py, frontend/src/constants.js, frontend/src/dashboard.js, frontend/src/views/jenkinsjobanalysis.js, frontend/src/widgets/filterheatmap.js, frontend/src/widgets/index.js
Adding a new widget for a heatmap that collects runs based off of a filter. Users can specify a list of filters, number of builds, and a group_field to get a heatmap of runs that fit those parameters. Open to suggestions especially on how I implemented the backend. I sort of had to retrieve all of the most recent run results and then manually filter them to make sure they're in the right order and then only return x amount of runs based on what the user passed for builds. Frontend is pretty much the exact same as jenkins-heatmap.
=> New filter-heatmap widget for making flexible heatmaps

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Fix #441 where project id was not being applied to the results
* Fix an issue where a run ID in a junit XML filename was not used in Ibutsu
* Fix an issue in reports where the report ID went missing
* Some bug fixes for tokens and projects
=> Release 2.5.1

CHANGELOG.md, backend/ibutsu_server/openapi/openapi.yaml, backend/setup.py, frontend/package.json
* Fix up the colours of the fonts of various charts/widgets
* Migrate to use the built-in TreeView component from PatternFly
* Check if values are None and default to 0 if they are (fix #418)
* Add the ability to disable SSL verification
* Fix the download buttons so that they actually download the artifact or report
* Parameter should be a string, force the value to be a string
* Expose the Keycloak login environment in App Interface
=> Release 2.5.2

frontend/src/components/add-token-modal.js
It seems that the onChange event changed function signature sometime between when I initially implemented it, and now. Fixing that makes all our problems go away, amazing!
=> Fix expiry date validation by updating onChange handler

backend/ibutsu_server/tasks/__init__.py
When disconnected from redis, the worker does not recover and begin consuming tasks again.
https://github.com/celery/celery/issues/8030 suggests adding socket timeout options -- which is what the goal of this PR is.
=> Set socket timeouts for redis

backend/ibutsu_server/controllers/admin/user_controller.py
I found this small bug when playing with Ibutsu locally and tried to have more users than default admin:
**Bug:**
```
?fix-local-dev-setup ~/Documents/WORK/TOOLS/ibutsu-server> curl http://localhost:8080/api/user -H "Accept: application/json" -H "Authorization: Bearer $IBUTSU_TOK"
{
"email": "admin@example.com",
"group_id": null,
"id": "58180e1a-4cd4-4f18-8d73-295871bae8d6",
"is_active": true,
"is_superadmin": true,
"name": "Administrator"
}
(.iqe-env) ?fix-local-dev-setup ~/Documents/WORK/TOOLS/ibutsu-server> curl -X 'POST' http://localhost:8080/api/admin/user -H "Accept: application/json" -H "Authorization: Bearer $IBUTSU_TOK" -H 'Content-Type: application/json' -d '{"email": "user-example-1@domain.com", "is_active": true, "is_superadmin": false, "name": "User example one"}'
"The user …
```
=> Fix creation user by admin

ocp-templates/mpp/backend.yaml
- we need to add https:// protocol to the FRONTEND_URL/BACKEND_URL values, otherwise the SSO auth will be failing with an invalid redirect-uri error
- JWT secret + var must be used in the backend pod, without it we get error `ibutsu_server.errors.IbutsuError: JWT_SECRET is not defined in configuration or an environment variable`
=> Update OCP mpp backend templates

frontend/package.json
Resolves react-chart dependency issue. For more info see https://github.com/patternfly/patternfly-react/issues/10064
Note that PR has both `resolutions` (for yarn) and `overrides` (for npm). We might need to take a look later how to deal with it and use only one package manager because our tests use yarn and I see yarn is mentioned in the doc but npm is used in Dockerfile to build FE
=> Add resolution to victory core package

ocp-templates/mpp/backend.yaml, ocp-templates/mpp/postgres.yaml
With defaults, pg_restore connection was closed when restoring from backup file:
```
2024-02-19 11:53:43.374 UTC [1] LOG:  server process (PID 2321) was terminated by signal 9: Killed
2024-02-19 11:53:43.374 UTC [1] DETAIL:  Failed process was running: COPY public.import_files (id, content, import_id) FROM stdin;
```
=> increase requests/limits for postgresql pod

backend/ibutsu_server/filters.py, backend/ibutsu_server/widgets/filter_heatmap.py, backend/ibutsu_server/widgets/jenkins_heatmap.py, backend/ibutsu_server/widgets/result_aggregator.py, backend/ibutsu_server/widgets/run_aggregator.py
This is going to help us avoid backend failures with 500 as we didn't check what user put into some fields and python had issues with it. Example, when user put into `group field` incorrect value `"component=foo"`, as the result backend fails as Run object doesn't have this attribute:
```
File "/app/ibutsu_server/filters.py", line 84, in string_to_column
column = getattr(model, field)
AttributeError: type object 'Run' has no attribute 'component=foo'
```
If there are some issues to find a column - we return None from `string_to_column` helper function. Then widgets that have this field mandatory will return empty data
=> Control sensitive fields better

.pre-commit-config.yaml, backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/health_controller.py, backend/ibutsu_server/controllers/login_controller.py, backend/ibutsu_server/db/util.py, backend/ibutsu_server/models/base_model_.py, backend/ibutsu_server/tasks/db.py, backend/ibutsu_server/tasks/reports.py, backend/ibutsu_server/test/test_login_controller.py, backend/ibutsu_server/util/count.py, backend/ibutsu_server/util/keycloak.py, backend/ibutsu_server/util/oauth.py, backend/ibutsu_server/util/query.py, backend/main.py, backend/wsgi.py, frontend/public/settings.js, scripts/ibutsu-pod.sh
Having issues in podman 5 with pasta networking defaults, using localhost to resolve other containers in the pod.
Hit this moving to podman 5 with Fedora 40. I'm actually using podman without docker, and have even added a podman.sock alias trying to resolve this.
I don't think changing to 127.0.0.1 in these places is detrimental, where using localhost will be dependent on the podman version, and whether rootful network is being used. 
This manifests in three places:
Define constant and import it for references to `localhost`, changing them to 127.0.0.1. These are only used as a default, and won't be relevant in production.
An error will occur in login.json and no login options will render - similar to the issue reported for SSO integration when CA certs are not setup for the client. …
=> Update from localhost to 127.0.0.1

backend/ibutsu_server/__init__.py, backend/ibutsu_server/constants.py, backend/ibutsu_server/controllers/admin/project_controller.py, backend/ibutsu_server/controllers/admin/user_controller.py, backend/ibutsu_server/controllers/artifact_controller.py, backend/ibutsu_server/controllers/dashboard_controller.py, backend/ibutsu_server/controllers/group_controller.py, backend/ibutsu_server/controllers/health_controller.py, backend/ibutsu_server/controllers/import_controller.py, backend/ibutsu_server/controllers/login_controller.py, backend/ibutsu_server/controllers/project_controller.py, backend/ibutsu_server/controllers/report_controller.py, backend/ibutsu_server/controllers/result_controller.py, backend/ibutsu_server/controllers/run_controller.py, backend/ibutsu_server/controllers/task_controller.py, backend/ibutsu_server/controllers/user_controller.py, backend/ibutsu_server/controllers/widget_config_controller.py, backend/ibutsu_server/controllers/widget_controller.py, backend/ibutsu_server/test/__init__.py, backend/ibutsu_server/test/test_login_controller.py, backend/ibutsu_server/util/admin.py, backend/ibutsu_server/util/login.py, backend/ibutsu_server/util/query.py, backend/ibutsu_server/util/uuid.py, scripts/ibutsu-pod.sh
Use the module imports instead of magic numbers. They probably won't change but some linting/formatting/mypy rules start to enforce it.
These were all the uses of the status codes that I found throughout the backend codebase. There may be some others that are hiding but it's not critical to get 100% of them in this PR.
=> Use httpstatus module

frontend/src/components/ibutsu-header.js
The pagination for project fetch for the header is hardcoded to 10 and doesn't iterate over pages.
This also indicates an issue with the controller implementation, because when filtering you still have invisble projects, because it will apply title filters *after* the page limit is applied.
Confirmed with admin/non-admin setting on an account. Without admin, the user did not have all 10+ projects that exist in RH production instance now, and could see the previously invisible project.
This was triggered by having more than 10 projects in production instance.
=> "Fix" invisible projects

README.md, docs/source/examples/okd-template.rst, docs/source/user-guide/filter-help.rst, ocp-templates/README.md, ocp-templates/prod/flower.yaml, ocp-templates/stage/backend.yaml, ocp-templates/stage/flower.yaml, ocp-templates/stage/frontend.yaml, ocp-templates/stage/scheduler.yaml, ocp-templates/stage/worker.yaml, scripts/make-release.sh
Update references to account for the GitHub renaming of `master` branch to `main`.
The open PRs were updated automatically by GitHub, but any local environments will need to be handled by the owner.
=> Rename master branch to main

frontend/src/app.js, frontend/src/components/ibutsu-header.js, frontend/src/dashboard.js
The dashboard widgets weren't clearing on project change because the context still held the dashboard from the previous project.
=> Fix dashboard clearing on project change

frontend/src/widgets/filterheatmap.js, frontend/src/widgets/importancecomponent.js
Widgets that filter results and runs create URLs that belong to projects, this PR enables the project routing on mentioned widgets
=> Enable project routing in widgets URLs

frontend/src/result-list.js, frontend/src/run-list.js, scripts/ibutsu-pod.sh
Reported by Eva Sebestova
When applying filters to the run page, the URL was improperly formed for the navigation call.
I also fixed the 'apply active filters to report' links for both run-list and result-list
https://issues.redhat.com/browse/IQE-3166
=> Fix run filtering and apply filters to report buttons

backend/ibutsu_server/constants.py, backend/ibutsu_server/widgets/importance_component.py, frontend/src/widgets/importancecomponent.js
As done in other widgets, like Jenkins heatmap, it would be useful to allow users to decide if they want to count skipped tests or not in Importance by Component widget.
=> Add count_skips field to Importance by Component widget

backend/ibutsu_server/widgets/importance_component.py
Importance by Component widget uses the _job name_ to fetch runs and the _build number_ and _component_ to group the results. However, there are cases where different jobs may have the same build number and component (for example, two different jobs for stage and prod that contains results for the same component).
This PR modifies the field used in the query from `build_number` to `source` which has more information to not mix runs.
=> Use source instead of build number when filtering results in Importance by Component widget

frontend/eslint.config.mjs, frontend/src/app.js, frontend/src/components/ibutsu-header.js, frontend/src/components/sidebar.js, frontend/src/components/user-dropdown.js, frontend/src/dashboard.js, frontend/src/login.js, frontend/src/services/context.js
Conversion of the Dashboard component to React functional.
1. Allows for direct use of React and router-dom hooks.
2. Better behavior for utilizing the URL params, simpler filtering behavior.
3. Many 1-line functions moved to callbacks within the JSX.
4. useEffect replacing componentDidMount, with direct correlation to the relevant state or contextual dependency.
5. Removal of `ActiveDashboard` from the context, now correctly implemented with state in Dashboard
6. Addition of `defaultDashboard` to the context, now correctly set when project selection changes
https://issues.redhat.com/browse/IQE-3256
=> Convert dashboard to functional

frontend/eslint.config.mjs, frontend/package.json, frontend/src/app.js, frontend/src/app.test.js, frontend/src/components/FileUpload.spec.cy.js, frontend/src/components/admin-page.js, frontend/src/components/fileupload.js, frontend/src/components/ibutsu-header.js, frontend/src/components/ibutsu-page.js, frontend/src/components/index.js, frontend/src/components/profile-page.js, frontend/src/components/result.js, frontend/src/components/toast-wrapper.js, frontend/src/constants.js, frontend/src/dashboard.js, frontend/src/index.js, frontend/src/pages/profile/tokens.js, frontend/src/pages/profile/user.js, frontend/src/run.js, frontend/src/services/context.js, frontend/src/utilities.js, frontend/yarn.lock
Introduce react-toastify in addition to the migration, in order to get rid of the eventEmitter and improve the notifications pattern.
The ToastContainer has been placed in the IbutsuPage and ProfilePage, where the notifications are relevant.
Notification hooks have been moved from the header to the actual FileUpload that produces them. I left FileUpload as a class component but removed the beforeUpload and afterUpload hooks as I don't believe it makes sense to inject notification hooks through those function callbacks.
=> Convert IbutsuHeader to functional component

frontend/src/components/sidebar.js
Context wasn't being used correctly in sidebar
Move behavior to useEffect to fetch views on project selection
=> Sidebar useEffect conversion

frontend/src/app.js, frontend/src/report-builder.js
Pretty straightforward migration, dropped one unused state item for total pages.
Had to use callback functions for the useEffect hooks
=> Convert ReportBuilder to functional

frontend/src/components/index.js, frontend/src/components/result.js, frontend/src/components/tabs.js, frontend/src/run.js, frontend/src/views/accessibilityanalysis.js
The Run view is rendering multiple tabs for requirements report artifacts, but this diff is not changing the tab/artifact mapping in the run component. It's only changing the icon to be passed as a react node instead of the object.
The run component will be converted in the feature branch in a separate PR, and the behavior for artifact iteration will be addressed there.
=> Convert TabTitle

frontend/src/components/edit-widget-modal.js, frontend/src/components/index.js, frontend/src/dashboard.js
=> Convert EditWidgetModal

frontend/src/admin.js, frontend/src/pages/admin/project-list.js
document is still re-rendering continuously it's just not visible other than the doc title
Table is rendering, filtering is working, delete is working, and there's a new empty state displayed instead of the table 'no results found' view.
=> Convert projectlist

.pre-commit-config.yaml, backend/ibutsu_server/constants.py, backend/ibutsu_server/util/keycloak.py, frontend/src/services/keycloak.js
In the itless environment, the Keycloak authentication instance was upgraded.  In this upgrade the "/auth" endpoint was deprecated.  This logic keeps the existing logic with the hardcoded "login/auth/keycloak" endpoint, but also adds in the availability to overwrite that by using the keycloakAuthPath (in the frontend) and KEYCLOAK_AUTH_PATH (foir backend) environment variables.
=> Added logic for different keycloak auth paths

frontend/src/components/artifact-tab.js, frontend/src/components/classification-dropdown.js, frontend/src/components/classify-failures.js, frontend/src/components/download-button.js, frontend/src/components/filtertable.js, frontend/src/components/index.js, frontend/src/components/metafilter.js, frontend/src/components/test-history.js, frontend/src/pages/admin/project-list.js, frontend/src/pages/admin/user-list.js, frontend/src/pages/profile/tokens.js, frontend/src/report-builder.js, frontend/src/result-list.js, frontend/src/run-list.js, frontend/src/run.js, frontend/src/utilities.js, frontend/src/views/accessibilityanalysis.js, frontend/src/views/accessibilitydashboard.js, frontend/src/views/compareruns.js, frontend/src/views/jenkinsjob.js
Working multi-classification and single classification
Tested on run classify failures tab, and on result page.
=> Convert ClassifyFailureTable to functional

frontend/src/components/classify-failures.js, frontend/src/components/metafilter.js, frontend/src/components/view.js, frontend/src/views/compareruns.js, frontend/src/views/index.js
This component has extremely limited use in production, and has behaviors in prod that should be addressed anyway.
I'm going to scope the work for the current effort, the component is in a clean enough state that it won't cause issues, but is not fully usable.
=> Convert CompareRunsView

.pre-commit-config.yaml, backend/ibutsu_server/test/__init__.py, backend/ibutsu_server/util/keycloak.py, frontend/src/services/keycloak.js
Redid the keycloak auth logic.  Originally I was changing the internal keycloak authentication path that Ibutsu itself uses.  Whereas in the updated version of keycloak, the auth path used to Keycloak itself has been updated. Additionally removed references to keycloak auth path for the frontend deployment because that is not needed.
=> Modified keycloak auth path logic
